### ISSUE TITLE
Old appVersion in latest chart

### ISSUE THREAD

**Issue by mkhpalm** [verdaccio/charts#102]
The current latest version of the verdaccio chart defaults to a version with various bugs in it

* Currently set to v5.5.0: https://github.com/verdaccio/charts/blob/b8dda9a60f43988702a8e44802396f868a958fd6/charts/verdaccio/Chart.yaml
* Suffers from: https://github.com/verdaccio/verdaccio/issues/3006
* Suffers from: https://github.com/verdaccio/charts/issues/77
* Current version is v5.14.0: https://github.com/verdaccio/verdaccio/releases/tag/v5.14.0

This is a little unexpected when trying verdaccio for the first time it comes up out of the box with various issues

**Comment by juanpicado** [comment]
Hi, first one is easy fix, would you like PR?
