### ISSUE TITLE
Crash loop in Kubernetes with Helm

### ISSUE THREAD

**Issue by alamothe** [verdaccio/charts#103]
**Your Environment**
  
 * **verdaccio version**: 5.5.0
 * **node version**: Using docker image
 * **package manager**: Using docker image
 * **os**: Usign docker image
 * **platform**: Google cloud + kubernetes + helm

**Describe the bug**

After deploying to GKE with Helm, it will go into a crash loop. The logs show this as the last log line:
```
warn --- invalid address - http://0.0.0.0:tcp://10.116.12.227:4873, we expect a port (e.g. "4873"), host:port (e.g. "localhost:4873") or full url (e.g. "http://localhost:4873/")
```

**To Reproduce**

- Deploy to GKE using Helm without any changes

I can also reproduce with:
```bash
kubectl run test --image=verdaccio/verdaccio:5.5.0 -i --tty --rm
If you don't see a command prompt, try pressing enter.
 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- invalid address - http://0.0.0.0:tcp://10.116.12.227:4873, we expect a port (e.g. "4873"), host:port (e.g. "localhost:4873") or full url (e.g. "http://localhost:4873/")
```

**Expected behavior**

- No crash loop

**Screenshots, server logs, package manager log**

Added log

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

Config file is from helm, no changes

**Environment information**

NA

**Debugging output**

NA

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by Keloran** [comment]
this worked for me, https://github.com/verdaccio/charts/issues/77#issuecomment-1061880922

**Comment by renatomjr** [comment]
I think the reason is related to the situation described in the README:

> Note: Avoid release name verdaccio, otherwise, Kubernetes-generated environment variables may get into conflict with Verdaccio's own environment variables in the Pod itself. In case you insist naming the release verdaccio, to mitigate the problem, you can use either nameOverride or fullnameOverride to have a different name for the service.

Changing the release name to something else than verdaccio should works.

**Comment by imvishalvyas** [comment]
I fixed the problem. There was a problem with the release's name. I changed the name of the helm release and it worked.
