### ISSUE TITLE
README is missing Artifact Hub

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/charts#14]
The new services (still in alpha) do not display the README and I don't know why. It might be a bug in their side, just in case I write down this.

https://artifacthub.io/package/chart/verdaccio/verdaccio

**Comment by orefalo** [comment]
I don't understand your problem

**Comment by juanpicado** [comment]
It seems the URL did change, right one is https://artifacthub.io/packages/helm/verdaccio/verdaccio

Here the issue (seems related):

This works: https://charts.verdaccio.org/index.yaml
This https://charts.verdaccio.org/ 404
The page https://artifacthub.io/packages/helm/verdaccio/verdaccio display there is no README (why? how to fix it?)

Something like like https://artifacthub.io/packages/helm/stable/tomcat

**Comment by todpunk** [comment]
I'm unfamiliar with artifacthub, but it seems that you just need a `README.md` file in the same directory as Chart.yaml and it will show up in most repo managers.  Bitnami's example is what I most recently leaned on, but glancing at others yields the same results: https://github.com/bitnami/charts/tree/master/bitnami/common

**Comment by juanpicado** [comment]
Done. I guess will be indexed eventually hopefully

At least I fixed accidentally #16 🙃  https://charts.verdaccio.org/

**Comment by kav** [comment]
I think for this to work we've got to move the chart files into the root directory or the readme into charts/verdaccio. Any thoughts? I don't know that we need `charts/verdaccio` unless the project is planning to add more independently installable app charts for other applications.

**Comment by juanpicado** [comment]
> I think for this to work we've got to move the chart files into the root directory or the readme into charts/verdaccio. Any thoughts? I don't know that we need `charts/verdaccio` unless the project is planning to add more independently installable app charts for other applications.

For me is fine, I think initially https://github.com/verdaccio/charts/pull/1 was created like that with the initial idea to scale it, but I think we don't need more charts, only one.

**Comment by juanpicado** [comment]
I know how to fix it, the README.md must be inside the package, it just matter to move the README.md to the chart folder.
