### ISSUE TITLE
Website 404

### ISSUE THREAD

**Issue by jhonmike** [verdaccio/charts#16]
when accessing today the website was returning 404

https://charts.verdaccio.org/ 

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/2499937/79566769-7f218700-8089-11ea-91f2-1a1a4d64e91e.png">

**Comment by juanpicado** [comment]
Yeah ... we need a landing page. But the index.yaml works fine

**Comment by kav** [comment]
Do we want to redirect to the main verdaccio page? Or maybe here even?

**Comment by juanpicado** [comment]
I’ve seen other charts and I would prefer to have a HTML with the logo verdaccio and some flexible info. That might have some documentation.

**Comment by juanpicado** [comment]
It seems I fixed it somehow https://charts.verdaccio.org/ 😆 ...
