### ISSUE TITLE
customConfigMap support

### ISSUE THREAD

**Issue by arteal** [verdaccio/charts#25]
Hello, there is `customConfigMap` parameter in documentation, but it is not used anywhere.

I will make PR with implementation of this parameter. If this is some obsolete stuff and should be removed, then feel free to reject my PR, but then I will suggest to remove this from documentation. Thanks!

**Comment by kav** [comment]
Just want to say thanks for doing this and it looks great! As someone who uses the feature how do you feel about the name? I know that's what the docs call it but it seems like most of the time we, and other helm authors, are calling these kind of properties `existingX`; do you think we should use `existingConfigMap`? Happy to take the commit either way but thought you might be the perfect person to ask here.

**Comment by arteal** [comment]
Good, existing sounds better :)) I have changed it and I have also bumped Helm chart version in Helm chart definition. Hope it is fine.
