### ISSUE TITLE
Custom domain for charts

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/charts#4]
I'd prefer to have a custom domain instead `github.io`.  Ideas?

We have 2 domains, `verdaccio.dev` and `verdaccio.org`.

My bet:
* `charts.verdaccio.org`
* `helm.verdaccio.org`

... my point is I don't want to be strictly tight with GitHub infrastructure from the very beginning. I want to be able to move charts to another place in the future without force users to update helm the repo URL. 

@verdaccio/kubernetes @verdaccio/collaborators   thoughts on this?

**Comment by anikethsaha** [comment]
> * `charts.verdaccio.org`
> * `helm.verdaccio.org`

+1 for this.

**Comment by DanielRuf** [comment]
> +1 for this.

Also .org from my side.

**Comment by jhonmike** [comment]
I agree, you can now add a CNAME file at the root of the project with the desired domain, and in the future we can adjust the build to move the chart host.

About being `.org` or `.dev` I think it's more your decision

**Comment by DanielRuf** [comment]
> About being `.org` or `.dev` I think it's more your decision

Well, I see it like this:
Many still use and used `.dev` for local development and it is a new gTLD owned by Google. We had more problems with this than there should be. .org is well established, there should be no problems and it might cost less as there are more registrars who sell it.

**Comment by juanpicado** [comment]
`charts.verdaccio.org` would be then, I will set it up today thanks guys

**Comment by juanpicado** [comment]
Please test 🙃 

https://charts.verdaccio.org/

**Comment by DanielRuf** [comment]
I think the DNS takes some time.
Which TTL values are used?

```
curl https://charts.verdaccio.org/ --head
curl: (6) Could not resolve host: charts.verdaccio.org
```

**Comment by juanpicado** [comment]
1 hour, the default at Godaddy

**Comment by DanielRuf** [comment]
Seems it works now =)
<img width="1003" alt="Bildschirmfoto 2020-04-08 um 21 28 15" src="https://user-images.githubusercontent.com/827205/78825229-e4b5a980-79df-11ea-9b3d-d1da6fdeaa22.png">
