### ISSUE TITLE
#53 made breaking changes

### ISSUE THREAD

**Issue by kimxogus** [verdaccio/charts#55]
#53 made helm upgrade(without changes in `values.yaml`) errors like below
```plain
ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "enabled" in io.k8s.api.core.v1.SecurityContext
ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext
```
```plain
cannot patch "npm-registry-verdaccio" with kind Deployment: Deployment.apps "npm-registry-verdaccio" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"npm-registry", "app.kubernetes.io/name":"verdaccio"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

It looks #53 should have made a major version bump, not a minor version bump.

**Comment by juanpicado** [comment]
fyi @rblaine95

**Comment by rblaine95** [comment]
Ah, thank you for this, you're right, the removal of `securityContext.enabled` and the shift of `securityContext.fsGroup` -> `podSecurityContext.fsGroup` alone should have made #53 a major bump and not a minor!

The Deployment Selector Labels also should definitely have made it a major bump!

My apologies.

Here are the kubernetes `v1.17` API spec for [`podSecurityContext`](https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podsecuritycontext-v1-core)
And here's the Container [`securityContext`](https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#securitycontext-v1-core)
