### ISSUE TITLE
Failed to create Ingress when migrating from 2.0.1 to 2.1.0 chart

### ISSUE THREAD

**Issue by petarGitNik** [verdaccio/charts#57]
I tried to upgrade from version 2.0.1 to version 2.1.0 but fails with error:

```
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "npm.example.com" and path "/" is already defined in ingress default/verdaccio-verdaccio: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "npm.example.com" and path "/" is already defined in ingress default/verdaccio-verdaccio
```

Why does it fail for the existing resource? The ingress was created when chart was deployed for the first time.

**Comment by juanpicado** [comment]
@petarGitNik could you try https://github.com/verdaccio/charts/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R176 ?

**Comment by petarGitNik** [comment]
I'll try after the release, and let you know if that resolved the issue.

**Comment by rblaine95** [comment]
It looks like it may be related to [this](https://github.com/helm/helm/pull/7649) helm issue.

Can you try annotating the existing Ingress with:
```yaml
meta.helm.sh/release-name: <RELEASE_NAME>
meta.helm.sh/release-namespace: <RELEASE_NAMESPACE>
```
And then doing a `helm upgrade`?

I believe it may be related to the label rework of #53. The new/reworked labels causes Helm to 'forget' it managed the ingress and then tries to create a new ingress which causes an "existing resource" conflict.

**Comment by petarGitNik** [comment]
Yes. It is caused by #53 . (See https://github.com/verdaccio/charts/commit/e36e307cf4b193eaf45cec8ca88a4c9158e29517#diff-4e02e6703c54469251c1e14ced009c009e3df71458f35d5e242e164e8e9039bcL14-R25). The old chart was deployed as `verdaccio` and all other labels are `verdaccio-verdaccio`. When I try to upgrade, a bunch of new resources get crated, and oldresources keep on existing. This was a breaking change.

I've resolved the issue by changing `fullnameOverride` in my values to `verdaccio-verdaccio`.

**Comment by todpunk** [comment]
For future onlookers that might hit this, I set my `fullnameOverride` to `npm-registry-verdaccio` which involved the release name `npm-registry` into the mix, so if you don't use `verdaccio` as your release name, be careful. I don't believe this will work with PVCs, so be careful to set the reclaimPolicy on your PV so you don't lose data if that's something to be avoided.

If you, dear reader, do not already have a backup solution in case something goes wrong with the upgrade, a Velero backup may help as you can simply delete the whole release, upgrade with the `fullnameOverride` and restore the resources needed (if you have it isolated in its own namespace this is trivial, see their docs).
