### ISSUE TITLE
Support for npm token API

### ISSUE THREAD

**Issue by Splaktar** [verdaccio/charts#64]
In the [v5 migration guide](https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide) `npm token` is mentioned that it is still supported but had [some updates](https://github.com/verdaccio/verdaccio/pull/2145).

However, when I try to use it against my installation done via this Helm Chart, I get the following
```bash
r$ npm token
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry-staging.example.com/-/npm/v1/tokens - File not found
$ npm token create
npm password: 
npm ERR! code E404
npm ERR! 404 Not Found - POST https://registry-staging.example.com/-/npm/v1/tokens
```
Is something in this chart not configured to support this `v1/tokens` API or is there some configuration that I need to add for it?

**Comment by juanpicado** [comment]
Enable the experiment https://github.com/verdaccio/verdaccio/blob/5.x/conf/default.yaml#L79 

The bug is is not enabled by default, but it will be in the next release.

**Comment by Splaktar** [comment]
That works great, thank you! And now that you mentioned that it is in experiments, I also found it in the docs [here](https://verdaccio.org/docs/en/configuration#experiments).
