### ISSUE TITLE
Verdaccio Pod fails to start up when the Helm release is named "verdaccio"

### ISSUE THREAD

**Issue by zzvara** [verdaccio/charts#66]
Verdaccio Pod fails to start up when the Helm release is named "verdaccio".

Then, Kubernetes will create a service named "verdaccio", which will create an environment variable VERDACCIO_PORT in the Pod itself. That probably conflicts with a Verdaccio environment variable, thus, corrupting the startup of the Verdaccio service.

```
we expect a port (e.g. "4873"), host:port (e.g. "localhost:4873") or full url (e.g. "http://localhost:4873/")
```

**Comment by pshanoop** [comment]
You can use either `nameOverride` or `fullnameOverride` to have a different name for the service.
You can also use a release name different from `verdaccio`

**Comment by zzvara** [comment]
Sure, I just think this could be documented because naming the release `verdaccio` is very tempting. :-)

**Comment by juanpicado** [comment]
wanna PR @zzvara ? :) I'm very fast merging.

**Comment by draeron** [comment]
PodSpecs should disable the service links. Reason is k8s will override VERDACCIO_PORT with the service data.

```
enableServiceLinks: false
```

doc: https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
