### ISSUE TITLE
Enable private repo auth header injection via a Kubernetes Secret

### ISSUE THREAD

**Issue by Joon** [verdaccio/charts#94]
**Is your feature request related to a problem?**
When deploying Verdaccio in Kubernetes via Helm, I have to embed a basic auth header in the Verdaccio configmap. The Config Map is not a good place to store secrets because it is accessible to most users in a K8s cluster. 

**Describe the solution you'd like**
Instead of using config maps for sensitive issues, Kubernetes has a Secret feature which is more secure. These secrets can be bound to environment variables, which in turn can then be accessed by a process running inside the pod. The specific changes I think will enable this processing is as follows:
- Add a Helm parameter that is a config map for remote registry auth header values. Something like "remoteAuthHeaders: |-
corp_artifactory: value1
npmjs: value2"
- Update the Helm deployment to save these as secrets, and embed them in the deployed pod as environment variables, prefixed with "AUTH_" and suffixed with the upstream name, i.e. "AUTH_CORP_ARTIFACTORY" and "AUTH_NPMJS" for the above two examples
- Change Verdaccio so that the code that connects to upstream repos inspects the environment for a variable called AUTH_ $currentUpstreamName, and injects the value from the environment variable as an http Authenticate header in the format "Basic $envVarName"

**Describe alternatives you've considered**
At the moment I am using Configmaps in Kubernetes. This works but is not secure enough for our auditors.

**Additional context**
I would like to implement this, just wanted to discuss it here first to make sure it makes sense and there isn't a better alternative before I make the changes.

**Comment by juanpicado** [comment]
@Joon I am not sure if understand the request.  Currently uplinks have the ability to look for custom env variables for each uplink, eg

```yaml
uplinks:
  private:
    url: https://private-registry.domain.com/registry
    auth:
      type: bearer
      token_env: FOO_TOKEN
````
https://verdaccio.org/docs/uplinks

Is that what you mean?

**Comment by rblaine95** [comment]
@Joon, I've opened a WIP/Draft PR (#95) for injecting these environment variables.
