### ISSUE TITLE
Allow injection of environment variables from existing secret

### ISSUE THREAD

**Issue by LoicGombeaud** [verdaccio/charts#99]
In order to securely configure this chart in a GitOps workflow (namely with ArgoCD), I need:
- to inject secret environment variables into the container,
- and these secrets not to be stored in plain text in git.

A mechanism allowing for injection of environment variables stored in an externally-defined secret would thus be beneficial.

FYI for context, this is needed to configure the LDAP admin password for the `verdaccio-ldap` plugin, via the `LDAP_ADMIN_PASSWORD` environment variable.

**Comment by rblaine95** [comment]
Closing this via #100
